/**
 * @file journal.model.js
 * @description Mongoose schema for storing journal entries
 * along with emotion analysis results generated by the LLM.
 */
const mongoose = require("mongoose");

/**
 * @schema Journal
 * @property {ObjectId} userId - Reference to the user who created the journal entry
 * @property {String} text - The journal text written by the user
 * @property {String} ambience - Nature ambience selected by the user (forest, ocean, mountain)
 * @property {String} emotion - Emotion detected by the LLM
 * @property {Array<String>} keywords - Keywords extracted from the journal entry
 * @property {String} summary - Short summary generated by the LLM
 * @property {String} analysisStatus - Status of LLM analysis (pending, completed, failed)
 */
const journalSchema = new mongoose.Schema(
    {
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            index: true,
            required: true
        },
        text: {
            type: String,
            required: true
        },

        ambience: {
            type: String,
            enum: ["forest", "ocean", "mountain"],
            required: true
        },

        emotion: {
            type: String
        },

        keywords: {
            type: [String],
            default: []
        },

        summary: {
            type: String
        },
        analysisStatus: {
            type: String,
            enum: ["pending", "completed", "failed"],
            default: "pending"
        }
    },
    {
        timestamps: true
    }
);

module.exports = mongoose.model("Journal", journalSchema);